### ISSUE TITLE
The models and raw results need permission to access.

### ISSUE THREAD

**Issue by Xuchen-Li** [Azong-HQU/MMTrack#2]
Thank you for your wonderful work. Can you open permissions？

**Comment by Azong-HQU** [comment]
Thanks for your feedback. Models and Raw Results are now accessible.
[[Models](https://drive.google.com/file/d/1kM8qxwJHJg4HuZNPPTMFZZTGEdtASVAf/view?usp=sharing)], [[Raw Results](https://drive.google.com/drive/folders/14kCYrdcBebtORg4Pqw73goWUYDkJiSwL?usp=sharing)]

**Comment by Xuchen-Li** [comment]
Thanks!
